services:
  bobytdl-backend:
    container_name: bobytdl-backend
    image: whiteblobbob/bobytdl-backend
    networks:
      - public-proxy-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    volumes:
      - ./cookies.txt:/app/cookies.txt:rw
  bobytdl-frontend:
    container_name: bobytdl-frontend
    image: whiteblobbob/bobytdl-frontend
    networks:
      - public-proxy-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    env_file:
      - ./.env

networks:
  public-proxy-net:
    external: true