services:
  bobytdl-backend:
    container_name: bobytdl-backend
    build: ./backend
    image: whiteblobbob/bobytdl-backend
    ports:
      - "8001:8000"
    networks:
      - public-proxy-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    volumes:
      - ./backend/cookies.txt:/app/cookies.txt:rw
  bobytdl-frontend:
    container_name: bobytdl-frontend
    build: ./frontend
    image: whiteblobbob/bobytdl-frontend
    ports:
      - "8002:80"
    networks:
      - public-proxy-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    env_file:
      - ./frontend/.env

networks:
  public-proxy-net:
    external: true